export const GET_ORDERS_REQUEST='GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS='GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE='GET_ORDERS_FAILURE';

export const CONFIRMED_ORDERS_REQUEST='CONFIRMED_ORDERS_REQUEST';
export const CONFIRMED_ORDERS_SUCCESS='CONFIRMED_ORDERS_SUCCESS';
export const CONFIRMED_ORDERS_FAILURE='CONFIRMED_ORDERS_FAILURE';

export const PLACED_ORDERS_SUCCESS='PLACED_ORDERS_SUCCESS';
export const PLACED_ORDERS_REQUEST='PLACED_ORDERS_REQUEST';
export const PLACED_ORDERS_FAILURE='PLACED_ORDERS_FAILURE';

export const DELIVERED_ORDERS_REQUEST='DELIVERED_ORDERS_REQUEST';
export const DELIVERED_ORDERS_SUCCESS='DELIVERED_ORDERS_SUCCESS';
export const DELIVERED_ORDERS_FAILURE='DELIVERED_ORDERS_FAILURE';

export const SHIP_ORDERS_REQUEST='SHIP_ORDERS_REQUEST';
export const SHIP_ORDERS_SUCCESS='SHIP_ORDERS_SUCCESS';
export const SHIP_ORDERS_FAILURE='SHIP_ORDERS_FAILURE';

export const DELETE_ORDER_REQUEST='DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS='DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE='DELETE_ORDER_FAILURE';

export const CANCELED_ORDER_REQUEST='CANCELED_ORDER_REQUEST';
export const CANCELED_ORDER_SUCCESS='CANCELED_ORDER_SUCCESS';
export const CANCELED_ORDER_FAILURE='CANCELED_ORDER_FAILURE';

